name: Manual Workflow Dispatch 2

on:
  workflow_dispatch:
    inputs:
      # --- Базовые параметры ---
      region:
        type: choice
        options:
          - eu-west
          - us-east
          - ap-south
        default: eu-west
        description: 'Region for deployment'

      instance_count:
        type: number
        default: 1
        description: 'Number of instances to deploy (e.g., 1, 2, 5)'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display region
        run: echo "Deployment region: ${{ inputs.region }}"

      - name: Display instance count
        run: echo "Number of instances: ${{ inputs.instance_count }}"
