name: Manual Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      # --- Базовые параметры ---
      environment:
        description: 'Environment to deploy (e.g., staging, production)'
        required: true
        default: 'staging'
      version:
        description: 'Application version to deploy'
        required: false
        default: '1.0.0'
      deploy_user:
        description: 'User account for deployment'
        required: false
        default: 'deployer'
      region:
        type: choice
        options:
          - eu-west
          - us-east
          - ap-south
        default: eu-west
        description: 'Region for deployment'

      # --- Опции деплоя ---
      run_migrations:
        description: 'Whether to run database migrations'
        default: 'true'
      domain:
        description: 'Domain name for the application'
        default: 'example.com'
      clear_cache:
        description: 'Clear cache after deployment'
        default: false

      # --- Новые параметры ---
      config:
        type: choice
        options:
          - dev
          - prod
          - custom
        default: dev
        description: 'Configuration profile to use'
      ssl_enabled:
        description: 'Enable SSL certificate'
      max_retries:
        description: 'Maximum number of retries on failure'
      notifications:
        description: 'Send deployment notifications'
      timeout:
        description: 'Deployment timeout in seconds'
      log_level:
        type: choice
        options:
          - debug
          - info
          - warn
          - error
        default: info
      backup_before_deploy:
        description: 'Create a backup before deployment'
      auto_rollback:
        description: 'Automatically rollback on failure'
      custom_tags:
        description: 'Custom tags for this deployment (e.g., "feature-a", "hotfix")'
      deploy_time:
        description: 'Planned deployment time (for scheduling)'
        default: 'now'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display environment
        run: echo "Deploying to environment:${{ inputs.environment }}"

      - name: Display version
        if: inputs.version != ''
        run: echo "Deploying version:${{ inputs.version }}"

      - name: Display user
        run: echo "Deploying as user:${{ inputs.deploy_user }}"

      - name: Display region
        run: echo "Deployment region:${{ inputs.region }}"

      - name: Run database migrations?
        run: echo "Run migrations:${{ inputs.run_migrations }}"

      - name: Domain name
        run: echo "Domain:${{ inputs.domain }}"

      - name: Clear cache?
        run: echo "Clear cache:${{ inputs.clear_cache }}"

      - name: Configuration profile
        run: echo "Using configuration:${{ inputs.config }}"

      - name: SSL Enabled
        run: echo "SSL Enabled:${{ inputs.ssl_enabled }}"

      - name: Max Retries
        run: echo "Max Retries:${{ inputs.max_retries }}"

      - name: Notifications Enabled
        run: echo "Notifications Enabled:${{ inputs.notifications }}"

      - name: Timeout (seconds)
        run: echo "Timeout:${{ inputs.timeout }}"

      - name: Log Level
        run: echo "Log Level:${{ inputs.log_level }}"

      - name: Backup Before Deploy
        run: echo "Backup Before Deploy:${{ inputs.backup_before_deploy }}"

      - name: Auto Rollback
        run: echo "Auto Rollback:${{ inputs.auto_rollback }}"

      - name: Custom Tags
        if: inputs.custom_tags != ''
        run: echo "Custom Tags:${{ inputs.custom_tags }}"

      - name: Deploy Time
        run: echo "Deploy Time:${{ inputs.deploy_time }}"
